# Generated by Django 3.2.8 on 2021-10-31 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(db_index=True, unique=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('session_expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 16, 27, 9, 193001))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_db.users')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
