# Generated by Django 3.2.8 on 2021-11-09 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0002_auto_20211105_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 0, 37, 38, 26835)),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.BinaryField(null=True),
        ),
    ]
