# Generated by Django 3.2.8 on 2021-11-13 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0003_auto_20211110_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='user',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='sessions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 17, 50, 47, 898195)),
        ),
    ]
