# Generated by Django 3.2.8 on 2021-11-13 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0004_auto_20211113_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sessions',
            name='dt_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 0, 49, 47, 771305)),
        ),
        migrations.AddField(
            model_name='sessions',
            name='dt_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 0, 49, 47, 771305)),
        ),
    ]
